### PR TITLE
Add PHP 8.4 support

### PR DESCRIPTION
**Pull request by weierophinney**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | no
| BC Break      | no
| New Feature   | yes
| RFC           | no
| QA            | no

### Description

- Adds PHP 8.4 to the allowed constraints
- Bumps PHPUnit to a version known to be tested against 8.4
- Indents heredocs for readability

### CODE REVIEW

**Comment by weierophinney** [comment]
I'm able to resolve the phpcs issues. However, the PHP 8.4 ones appear to be due to having a version of composer that is outdated on CI; I'm unable to reproduce locally when I run the `composer update`/`composer update --prefer-lowest` commands.

**Comment by weierophinney** [comment]
The phpcs issues here I cannot reproduce locally, either (I fixed different issues reported when I ran it). Will try running with PHP 8.1 to see if that demonstrates the issue.

**Comment by weierophinney** [comment]
Cannot reproduce the phpcs issues locally either.

**Comment by gsteel** [comment]
LCS 3.0 is working OK in CI - Only a few pointless param/return types to fix. Can you just bump it to 3.0 to see if the problem is fixed?

**Comment by gsteel** [comment]
Also, psalm won't install on 8.4 so `.laminas-ci.json` will need an update

**Review by gsteel — APPROVED** [review]
Thanks @weierophinney :)

**Pull request merged**
