### PR TITLE
Prepare for Renovate with reusable workflows

### PR DESCRIPTION
**Pull request by ghostwriter**
|    Q          |   A
|-------------- | ------
| QA            | yes

### Description

Adding Renovate to Laminas, Mezzio repositories. https://gist.github.com/weierophinney/49ca8ae2b916d898dd3d4162b26ff41b

- Configure minimum supported PHP version
- Update composer dependencies
- Update to reusable `Continuous Integration` workflow
- Update to reusable `Automatic Releases` workflow

### CODE REVIEW

**Review by Ocramius — APPROVED** [review]

**Comment by Ocramius** [comment]
CI seems to be broken here

**Comment by weierophinney** [comment]
Looks like the Composer API changed? All "latest dependencies" runs are failing, and they appear to be issues with inheritance/type trees.

**Comment by Ocramius** [comment]
@ghostwriter this needs a rebase - should be green afterwards.

**Comment by boesing** [comment]
Probably fixed the failing tests in #46 
Thats really annoying when composer requires interfaces and then checks for specific implementations somewhere nested in their code.

Luckily, due to renovate, new releases from composer will be bumped here so we will get early feedback when something starts to break.

**Comment by ghostwriter** [comment]
Should I bump `composer/composer` to `^2.3.0-RC2`?

**Review by Ocramius — APPROVED** [review]
No need: `composer/composer` is already checked out at `2.3.0-RC2` in the upper boundaries CI jobs :)

Thanks @ghostwriter!

**Pull request merged**
